### ISSUE TITLE
cant describe the issue

### ISSUE THREAD

**Issue by xnplz** [Scarlaid/P-QoL#13]
Minecraft Crash Report:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/21/22, 8:38 PM
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of com.mojang.authlib.yggdrasil.YggdrasilUserApiService failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:134)
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient:670)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:424)
	at net.minecraft.client.main.Main.main(Main:199)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [blanket-client-tweaks.mixins.json:fixes.YggdrasilUserApiService_syncBlockListMixin] from phase [DEFAULT] in config [blanket-client-tweaks.mixins.json] from mod [blanket-client-tweaks] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method fetchBlockList in blanket-client-tweaks.mixins.json:fixes.YggdrasilUserApiService_syncBlockListMixin was not located in the target class com.mojang.authlib.yggdrasil.YggdrasilUserApiService. Using refmap Blanket Client tweaks-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:134)
	at net.minecraft.class_310.method_31382(class_310.java:670)
	at net.minecraft.class_310.<init>(class_310.java:424)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.16.10-zen1-1-zen
	Java Version: 17.0.2, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1745188408 bytes (1664 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 11
	Microarchitecture: whiskey Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: WhiskeyLake-U GT2 [UHD Graphics 620]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10096.48
	Virtual memory used (MB): 3526.27
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 91.61
	JVM Flags: 18 total; -XX:+UseG1GC -Xmx2G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=2 -XX:ParallelGCThreads=8 -Xmx2048M -Xss1M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementinfo: AdvancementInfo 1.18-pre5-fabric0.42.8-1.2.2
		advdebug: Advancements Debug 2.3.0
		animatica: Animatica 0.3+1.18
		architectury: Architectury 3.2.51
		armorhud: Simple armor hud 1.18-1.2.1
		autofish: Autofish 0.9.4
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 2.4.1+0
		betterbeds: Better Beds 1.2.0
		betterbiomeblend: Better Biome Blend 1.18.1-1.3.2-fabric
		betterdarkmode: Betterdarkmode 1.0.4
		betterf3: BetterF3 1.2.2
		bettertaskbar: Better Taskbar 1.1
		blanket-client-tweaks: Blanket Client-tweaks 1.0.0
		blue_endless_jankson: jankson 1.2.1
		boatiview: Boat Item View 0.0.3
		borderlessmining: Borderless Mining 1.1.1+1.18
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.6.54
		caffeineconfig: CaffeineConfig 1.0.0
		capetweaks: Cape Tweaks 1.0.0
		cateyes: Cat Eyes 2.0.1
		cem: Custom Entity Models 0.7.0
		chat_heads: Chat Heads 0.6.0
		chime: Chime 1.2.0
		citresewn: CITResewn 0.8.2+1.18.1
		cleancut: CleanCut 1.18-4.0-fabric
		clear-skies: Clear Skies 2.0.88
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.0+5
		com_github_wearblackallday_javautils: JavaUtils bd58640372
		com_ishland_c2me_libs_: libs 0.2.0+alpha.6.54
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.3.3
		continuity: Continuity 1.0.3+1.18
		craftpresence: CraftPresence 1.8.8
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		dashloader: DashLoader 3.0-rc14-1.18
		detailed-debug-pie: Detailed Debug Pie 1.2.1
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		dimthread: DimensionalThreading 1.2.6
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entity_texture_features: Entity Texture Features 2.1.3
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-ofcapes: Fabric OF Capes 2.0.0
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.2
		fabricskyboxes: FabricSkyBoxes 0.5.4
		fabrishot: Fabrishot 1.6.2
		fastchest: FastChest 1.2+1.18
		fastopenlinksandfolders: FastOpenResourcePacks 1.0.1
		ferritecore: FerriteCore 4.1.2
		freelook: freelook 1.1.0
		fullscreeno: fullscreeNO 1.0.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		hatlist: Hat List 1.2
		hidearmor: Hide Armor 2.5
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		indium: Indium 1.0.2-alpha2+mc1.18.1
		inventoryprofilesnext: Inventory Profiles Next 1.3.3
		io_airlift_aircompressor: aircompressor 0.21
		iris: Iris 1.2.0-pre
		itemmodelfix: Item Model Fix 1.0.3+1.18
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		languagereload: Language Reload 1.2.1
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.7
		malilib: MaLiLib 0.11.6
		mbp: More Block Predicates 1.3
		mcpppp: MCPPPP 0.6.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		modmanager: Mod Manager 1.2.2+1.18
		modmenu: Mod Menu 3.0.1
		morechathistory: MoreChatHistory 1.1.0
		netherportalfix: NetherPortalFix 9.0.0
		nightvisionflashbegone: Night Vision Flash be gone! 1.1.0
		no_nether_portal_overlay: No Nether Portal Overlay 1.0.2
		nochatlag: NoChatLag 1.0.0
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		ordinarytweaks: SomeOrdinaryTweaks 1.1.0
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_yaml_snakeyaml: snakeyaml 1.29
		parry: Parry 1.3+1.18
		pinglist: PingList 1.3.3
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.1.0
		puzzle-base: Puzzle Base 1.1.0
		puzzle-emissives: Puzzle Emissive Textures 1.1.0
		puzzle-gui: Puzzle GUI 1.1.0
		puzzle-models: Puzzle Models 1.1.0
		puzzle-splashscreen: Puzzle Splash Screen 1.1.0
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		smoke_suppression: Smoke Suppression 1.0.8+MC1.18-1.18.1
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		spectater: Spectater 2.0.1
		spruceui: SpruceUI 3.3.2+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		statuseffecttimer: Status Effect Timer 1.1.0+1.18.1
		tiefix: TieFix 1.9.0
		timeoutout: TimeOut Out 1.0.0+1.18
		tooltipfix: ToolTip Fix 1.0.4-1.18
		viafabric: ViaFabric 0.4.5+244-main
		viafabric-mc118: ViaFabric for 1.18 0.4.5+244-main
		viaversion: ViaVersion 4.1.1-SNAPSHOT
		yosbr: YOSBR 0.1.1
	Launched Version: Fabric 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)
```
k thanks

**Comment by Scarlaid** [comment]
which modpack version are you using?

**Comment by xnplz** [comment]
cái mới nhất

**Comment by Scarlaid** [comment]
không thể tái hiện lại crash của npl, đang dùng modpack mới nhất đây

**Comment by Scarlaid** [comment]
relaunch xong dùng NotEnoughCrashes gửi link log nhé

**Comment by xnplz** [comment]
kìa không vào được game mà đòi relaunch

**Comment by Scarlaid** [comment]
NotEnoughCrashed nó cho phép **launch game at crash**, log sẽ đc convert ở dạng web

**Comment by Scarlaid** [comment]
1 ví dụ cho mod
![image](https://user-images.githubusercontent.com/90851437/155143990-782b848f-57cc-475a-8939-59186f2c8579.png)

**Comment by xnplz** [comment]
aight imma

**Comment by xnplz** [comment]
no wonder how to do it btw fsck

**Comment by Scarlaid** [comment]
was this problem fixed?

**Comment by xnplz** [comment]
> no wonder how to do it btw fsck

no

**Comment by Scarlaid** [comment]
right
I think this only occur in Linux

**Comment by xnplz** [comment]
![ok](https://imgur.com/nC9Dk26)

Không chỉ cách thì close luôn nhé

**Comment by xnplz** [comment]
> right I think this only occur in Linux

happened in windows too you dumbass

**Comment by Scarlaid** [comment]
> > right I think this only occur in Linux
> 
> happened in windows too you dumbass

just dropped v1.0.9, tested on onboard graphics and it runs fine

**Comment by xnplz** [comment]
> > > right I think this only occur in Linux
> > 
> > happened in windows too you dumbass
> 
> just dropped v1.0.9, tested on onboard graphics and it runs fine
> 

The

**Comment by Scarlaid** [comment]
can u not
